server:
  port: 8080
  servlet:
    context-path: /api/v1

jwt:
  signerKey: +MNdgud6jTaWzQTdrzP94KVBp5CDRueECVPDgwMq9fufXQzhp4acQz88MIkAj8KC

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

open:
  api:
    title: Task Manager System Services Document
    version: v1.0.0
    description: API Task Manager System
    serverUrl: http://localhost:8080/api/v1
    serverName: Server Test

springdoc:
  swagger-ui:
    operationsSorter: method   # Sắp xếp theo HTTP method (GET, POST, PUT, DELETE)
    tagsSorter: alpha          # Sắp xếp các tag theo thứ tự bảng chữ cái