import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";

const nunitoSans = Nunito_Sans({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Task Manager System",
  description: "Generated by Trong Lam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} antialiased`}>
        <div className="flex h-full w-full bg-[#f3f4f6] text-black">
          <div className="sidebar w-1/5 p-5">sidebar</div>
          <div className="main w-full pr-1">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
