import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Sidebar from "@/components/sidebar/sidebar";

const nunitoSans = Nunito_Sans({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Task Manager System",
  description: "Generated by Trong Lam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} antialiased`}>
        <div className="flex h-full w-full bg-[#f3f4f6] text-black">
          <div className="sticky top-0 hidden h-screen w-1/5 bg-white md:block">
            <Sidebar />
          </div>
          <div className="main flex-1">
            <Navbar />
            <div className="p-4 2xl:px-10">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
